name: Build Docker Images

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - images/**

jobs:
  push:
    name: "Build pterodactyl:${{ matrix.images }} Image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - debian-installer
          - steam
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.images }}
          file: ./images/${{ matrix.images }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/leliel91/pterodactyl:${{ matrix.images }}